IndiaDens/Admin/urls.py
from django.conf.urls  import *
from AdminHome import *

admin_urls = patterns('Admin.views',
    url(r'^$', HomePage.as_view()),
)

IndiaDens/Customers/urls.py
from django.conf.urls  import *
from views import *
from AravindViews import *

customer_urls = patterns('Customer.views',
    url(r'^$', HomePage.as_view()),
    url(r'^login', Login.as_view()),
    url(r'^listing-form', ListingForm.as_view()),
    url(r'^customer-menu', CustomerListPage.as_view()),
    url(r'^customer-listings', CustomerListings.as_view()),
    url(r'^confirm/([A-Za-z0-9]+)$', Confirm.as_view()),
    url(r'^mobile-confirm', MobileConfirm.as_view()),
    url(r'^reset-password', ResetPassword.as_view()),
    url(r'^close-account', CloseAccount.as_view()),
    url(r'^ListDelele', CustomerListDelete.as_view()),
    url(r'^callback-requests', CustomerCallBackRequests.as_view()),
    url(r'^ajaxcallback-request', AjaxCallBackRequest.as_view()),
    url(r'^visitor-reviews', VisitorReviewList.as_view()),
    url(r'^list-delete', ListingDelete.as_view()),
    url(r'^change-password', ChangePassword.as_view()),
    url(r'^customer-form', CustomerRegistration.as_view()),
)

IndiaDens/Staff/urls.py
from django.conf.urls  import *
from views import *

staff_urls = patterns('Staff.views',
    url(r'^$', HomePage.as_view()),
    url(r'^login', Login.as_view()),
    url(r'^logout', Logout.as_view()),
    url(r'^new-listings', NewListings.as_view()),
    url(r'^change-password', ChangePassword.as_view()),
    url(r'^executive-registration', ExecutiveRegistration.as_view()),
    url(r'^employee-form', Employee.as_view()),
    url(r'^listings', Listings.as_view()),
    url(r'^listingimages', ListingImages.as_view()),
    url(r'^listing-attributes', ListingAttributes.as_view()),
    url(r'^customer-list', CustomerList.as_view()),
    url(r'^customer-delete', CustomerDelete.as_view()),
    url(r'^customer-sale-listings', CustomerSaleListings.as_view()),
    url(r'^customer-rental-listings', CustomerRentalListings.as_view()),
    url(r'^cities', Location.as_view()),
    url(r'^mobilemessages', ListMessages.as_view()),
    url(r'^delete-messages', DeleteMessages.as_view()),
    url(r'^employee-list', ExecutivesList.as_view()),
    url(r'^zap-db', ZapDb.as_view()),
    
)

IndiaDens/urls.py
from django.conf.urls import *
from Admin.urls import admin_urls
from Staff.urls import staff_urls
from Customers.urls import customer_urls
from views import *
from searchviews import *

handler500 = 'djangotoolbox.errorviews.server_error'

urlpatterns = patterns('',
    ('^_ah/warmup$', 'djangoappengine.views.warmup'),
    ('^$', HomePage.as_view()),
    ('^Admin/', include(admin_urls)),
    ('^Staff/', include(staff_urls)),
    ('^[Cc]ustomer/', include(customer_urls)),
    ('^new-listing', NewListing.as_view()),
    ('^reg-confirmation', RegConfirmation.as_view()),
    ('^logout', Logout.as_view()), 
    ('^getcities', GetCityName.as_view()),
    ('^listing-info', ListingInfo.as_view()),
    ('^mobile-message', SaveMessage.as_view()),
    ('^testmail', TestMail.as_view()),
    ('^visitor-reviewsform', VisitorReviews.as_view()),
    ('^callback-requestform', CallBackRequest.as_view()),
    ('^testajax', TestAjax.as_view()),
    ('^get-listings', SearchResults.as_view()),
    ('^visitor-login', VisitorLogin.as_view()),
    ('^confirm-code', ConfirmVisitors.as_view()),
    ('^test-slide', TestSlide.as_view()),
    ('^ajax-customerlogin', AjaxCustomerLogin.as_view()),
    ('^ajax-confirmmobile', AjaxConfirmMobile.as_view()),
    ('^whatismyip', MyIP.as_view()),
    #('^display-cities', AutoDispalyCities.as_view()),
    url(r'^testmodel', TestModel.as_view()),
)

IndiaDens/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from __future__ import unicode_literals

from django.db import models

PROPERTY_TYPES = {10:'Apartments', 20:'Independent House', 25:' Villas', 30:'Pent House', 40: 'Farm House', 50:'Office Space', 100:'Residential Lands', 110:'Commercial Lands'}
PLANS = {0: 'Free', 1:'Silver', 2:'Gold', 3:'Platinum'}

class AuthGroup(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=80L, unique=True)
    class Meta:
        db_table = 'auth_group'

class AuthGroupPermissions(models.Model):
    id = models.IntegerField(primary_key=True)
    group = models.ForeignKey(AuthGroup)
    permission = models.ForeignKey('AuthPermission')
    class Meta:
        db_table = 'auth_group_permissions'

class AuthPermission(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50L)
    content_type = models.ForeignKey('DjangoContentType')
    codename = models.CharField(max_length=100L)
    class Meta:
        db_table = 'auth_permission'

class AuthUser(models.Model):
    id = models.IntegerField(primary_key=True)
    password = models.CharField(max_length=128L)
    last_login = models.DateTimeField()
    is_superuser = models.IntegerField()
    username = models.CharField(max_length=30L, unique=True)
    first_name = models.CharField(max_length=30L)
    last_name = models.CharField(max_length=30L)
    email = models.CharField(max_length=75L)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()
    class Meta:
        db_table = 'auth_user'

class AuthUserGroups(models.Model):
    id = models.IntegerField(primary_key=True)
    user = models.ForeignKey(AuthUser)
    group = models.ForeignKey(AuthGroup)
    class Meta:
        db_table = 'auth_user_groups'

class AuthUserUserPermissions(models.Model):
    id = models.IntegerField(primary_key=True)
    user = models.ForeignKey(AuthUser)
    permission = models.ForeignKey(AuthPermission)
    class Meta:
        db_table = 'auth_user_user_permissions'

class Cities(models.Model):
    cityid = models.IntegerField(primary_key=True, db_column='CityID') # Field name made lowercase.
    name = models.CharField(max_length=50L, db_column='Name', blank=True) # Field name made lowercase.
    stateid = models.IntegerField(null=True, db_column='StateID', blank=True) # Field name made lowercase.
    isnew = models.IntegerField(null=True, db_column='IsNew', blank=True) # Field name made lowercase.

    @property
    def State(self):
      state = None
      states = States.objects.filter(stateid = self.stateid)
      if states:
         state = states[0]
      
      return state
      
    class Meta:
        db_table = 'cities'

class Customers(models.Model):
    customerid = models.IntegerField(primary_key=True, db_column='CustomerID') # Field name made lowercase.
    customertype = models.IntegerField(null=True, db_column='CustomerType', blank=True) # Field name made lowercase.
    parentid = models.IntegerField(null=True, db_column='ParentID', blank=True) # Field name made lowercase.
    title = models.CharField(max_length=255L, db_column='Title', blank=True) # Field name made lowercase.
    subtitle = models.CharField(max_length=100L, db_column='SubTitle', blank=True) # Field name made lowercase.
    firstname = models.CharField(max_length=100L, db_column='FirstName', blank=True) # Field name made lowercase.
    lastname = models.CharField(max_length=100L, db_column='LastName', blank=True) # Field name made lowercase.
    address = models.CharField(max_length=255L, db_column='Address', blank=True) # Field name made lowercase.
    cityid = models.IntegerField(null=True, db_column='CityID', blank=True) # Field name made lowercase.
    stateid = models.IntegerField(null=True, db_column='StateID', blank=True) # Field name made lowercase.
    countryid = models.IntegerField(null=True, db_column='CountryID', blank=True) # Field name made lowercase.
    phone = models.CharField(max_length=100L, db_column='Phone', blank=True) # Field name made lowercase.
    fax = models.CharField(max_length=100L, db_column='Fax', blank=True) # Field name made lowercase.
    email = models.CharField(max_length=100L, db_column='EMail', blank=True) # Field name made lowercase.
    loginpwd = models.CharField(max_length=25L, db_column='LoginPwd', blank=True) # Field name made lowercase.
    locationmap = models.CharField(max_length=255L, db_column='LocationMap', blank=True) # Field name made lowercase.
    website = models.CharField(max_length=255L, db_column='WebSite', blank=True) # Field name made lowercase.
    logo = models.CharField(max_length=255L, db_column='Logo', blank=True) # Field name made lowercase.
    profile = models.CharField(max_length=255L, db_column='Profile', blank=True) # Field name made lowercase.
    deals = models.CharField(max_length=255L, db_column='Deals', blank=True) # Field name made lowercase.
    dealinglocations = models.CharField(max_length=255L, db_column='DealingLocations', blank=True) # Field name made lowercase.
    description = models.CharField(max_length=255L, db_column='Description', blank=True) # Field name made lowercase.
    keywords = models.CharField(max_length=255L, db_column='KeyWords', blank=True) # Field name made lowercase.
    confirmcode = models.CharField(max_length=25L, db_column='ConfirmCode', blank=True) # Field name made lowercase.
    updatedby = models.IntegerField(null=True, db_column='UpdatedBy', blank=True) # Field name made lowercase.
    isconfirmed = models.IntegerField(null=True, db_column='IsConfirmed', blank=True) # Field name made lowercase.
    emailcode = models.CharField(max_length=50L, db_column='EMailCode', blank=True) # Field name made lowercase.
    isemailverified = models.IntegerField(null=True, db_column='IsEMailVerified', blank=True) # Field name made lowercase.
    ismobileverified = models.IntegerField(null=True, db_column='IsMobileVerified', blank=True) # Field name made lowercase.
    mobilecode = models.CharField(max_length=50L, db_column='MobileCode', blank=True) # Field name made lowercase.
    isdeleted = models.IntegerField(null=True, db_column='IsDeleted', blank=True) # Field name made lowercase.
    class Meta:
        db_table = 'customers'

    @property
    def State(self):
      state = States.objects.get(stateid = self.stateid)
      return state

    @property
    def City(self):
      city = Cities.objects.get(cityid = self.cityid)
      return city
    
    @property
    def Rentalcounter(self):
      counter = 0
      listing_count = Rentals.objects.filter(customerid = self.customerid)
      for i in listing_count:
        counter = counter+1
      return counter
    @property
    def Salecounter(self):
      counter = 0
      listing_count = Sales.objects.filter(customerid = self.customerid)
      for i in listing_count:
        counter = counter+1
      return counter


class DjangoContentType(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100L)
    app_label = models.CharField(max_length=100L)
    model = models.CharField(max_length=100L)
    class Meta:
        db_table = 'django_content_type'

class DjangoSession(models.Model):
    session_key = models.CharField(max_length=40L, primary_key=True)
    session_data = models.TextField()
    expire_date = models.DateTimeField()
    class Meta:
        db_table = 'django_session'

class DjangoSite(models.Model):
    id = models.IntegerField(primary_key=True)
    domain = models.CharField(max_length=100L)
    name = models.CharField(max_length=50L)
    class Meta:
        db_table = 'django_site'

class Employees(models.Model):
    employeeid = models.IntegerField(primary_key=True, db_column='EmployeeID') # Field name made lowercase.
    firstname = models.CharField(max_length=50L, db_column='FirstName', blank=True) # Field name made lowercase.
    lastname = models.CharField(max_length=50L, db_column='LastName', blank=True) # Field name made lowercase.
    title = models.CharField(max_length=100L, db_column='Title', blank=True) # Field name made lowercase.
    branchid = models.IntegerField(null=True, db_column='BranchID', blank=True) # Field name made lowercase.
    designation = models.CharField(max_length=100L, db_column='Designation', blank=True) # Field name made lowercase.
    emailid = models.CharField(max_length=100L, db_column='EMailID', blank=True) # Field name made lowercase.
    loginpwd = models.CharField(max_length=25L, db_column='LoginPwd', blank=True) # Field name made lowercase.
    contactno = models.CharField(max_length=25L, db_column='ContactNo', blank=True) # Field name made lowercase.
    role = models.CharField(max_length=1L, db_column='Role', blank=True) # Field name made lowercase.
    businesscategory = models.IntegerField(null=True, db_column='BusinessCategory', blank=True) # Field name made lowercase.
    businessinfo = models.CharField(max_length=255L, db_column='BusinessInfo', blank=True) # Field name made lowercase.
    address = models.CharField(max_length=255L, db_column='Address', blank=True) # Field name made lowercase.
    city = models.CharField(max_length=100L, db_column='City', blank=True) # Field name made lowercase.
    stateid = models.IntegerField(null=True, db_column='StateID', blank=True) # Field name made lowercase.

IndiaDens/Staff/forms.py
from django import forms

class SaleListingImages(forms.Form):
    largeimage = forms.CharField(forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:40px'}),  required=True)
    description = forms.CharField(required=True, widget=forms.Textarea)

class ExecutiveRegForm(forms.Form):
    BUSINESS_CATEGORY = [
                   ('0', "Individual"),
                   ('1', "NetCafe"),
                   ('2', "E-seva"),
                   ]
    
    firstname = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON',  'style':'width:80px'}),  required=True)
    lastname = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:80px'}),  required=True)
    title = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:80px'}),  required=False)
    emailid = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:80px'}),  required=True)
    loginpwd = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'class' : 'txt-box1', 'autocomplete':'ON',}))
    contactno=forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':10, 'style':'width:80px'}),  required=True)
    business_category=forms.ChoiceField(choices = BUSINESS_CATEGORY, widget = forms.Select(attrs={'style':'width:100px'}), required=True)
    business_info = forms.CharField(widget = forms.Textarea(attrs={'autocomplete':'ON', 'size':30, 'rows' :3, 'style':'width:200px'}),  required=False)
    address = forms.CharField(required=True, widget=forms.Textarea(attrs={'rows':4, 'style':'width:200px'}))
    City = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:80px'}),  required=True)
    CityID = forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'ON', 'style':'width:40px'}), required=False)
    state = forms.ChoiceField(choices = [], widget = forms.Select(attrs={'style':'width:100px'}), required=True) 
    
    def __init__(self, *args, **kwargs):
      states = []
      if 'states' in kwargs:
        states = kwargs.pop('states')
      super(ExecutiveRegForm, self).__init__(*args,**kwargs)
      self.fields['state'].choices = states 
    
class EmployeeRegForm(forms.Form):
    
    firstname = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON',  'style':'width:90px',}),  required=True)
    lastname = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:90px'}),  required=True)
    emailid = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:100px'}),  required=True)
    loginpwd = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'class' : 'txt-box1', 'autocomplete':'ON',}))
    contactno=forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:100px'}),  required=True)
    address = forms.CharField(required=True, widget=forms.Textarea(attrs={'rows':4, 'style':'width:200px'}))
    City = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:80px'}),  required=True)
    CityID = forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'ON', 'style':'width:80px'}), required=False)
    state = forms.ChoiceField(choices = [], widget = forms.Select(attrs={'style':'width:100px'}), required=True)
    
    def __init__(self, *args, **kwargs):
      states = []
      if 'states' in kwargs:
        states = kwargs.pop('states')
      super(EmployeeRegForm, self).__init__(*args,**kwargs)
      self.fields['state'].choices = states  
            
  
  
  
  

IndiaDens/Admin/views.py
from IndiaDens.Admin import *


class HomePage(TemplateView):

  def get(self, request, *args, **kwargs):  
    content = {}
    return render_to_response("Admin/Index.html")


IndiaDens/templates/customers/ChangePassword.html
{% extends 'base.html' %}
{% block content %}
<div style="margin-left:20%; margin-right:25%; margin-top:10%">
<div class="round-rect" style="width:400px">
<form class="form-horizontal" action="change-password" method="post">
{% csrf_token %}
<p align="center" id="error">{{errmsg}}</p>
<legend style="font-size:16px; color:#FF6600">Change Password</legend>
<table width="100%" border="0" cellspacing="1" cellpadding="3">
  <tr>
    <td>Existing Password </td>
    <td><input name="currentpassword" type="password" class="form-control" id="currentPassword" placeholder="Current password"></td>
  </tr>
  <tr>
    <td>New Password </td>
    <td><input name="newpassword" type="password" class="form-control" id="newPassword" placeholder=" New Password"></td>
  </tr>
  <tr>
    <td>Confirm Password </td>
    <td><span class="checkbox">
      <label>
      <input name="confirmpassword" type="password" class="form-control" id="confirmPassword" placeholder="Confirm Password">
      </label>
    </span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><button type="submit" class="btn btn-default"  onClick="return checkPassword()">Save</button></td>
  </tr>
</table>
</form>
</div>
</div>
<script>
function checkPassword()
{
 var x = $("#currentPassword").val();
 var y = $("#newPassword").val();
 var z = $("#confirmPassword").val();
if(x=="")
 {
   $("#error").html("Please Enter current password");
   $("#currentPassword").focus()
   document.getElementById("error").style.color="red";
   return false;
 }
else if(y=="")
 {
   $("#error").html("Please Enter new Password");
   $("#newPassword").focus()
   document.getElementById("error").style.color="red";
   return false;
 }
 else if(z=="")
 {
   $("#error").html("Please Enter confirm Password");
   $("#confirmPassword").focus()
   document.getElementById("error").style.color="red";
   return false;
 }
 else
 {
 return true;
 }
}
</script>

{% endblock content %}

IndiaDens/templates/customers/CloseAccount.html
{% extends 'base-home.html' %}
{% block content %}
<div style="margin-left:20%; margin-right:25%; margin-top:10%">
<div class="round-rect" style="width:400px">
<form class="form-horizontal" method="post" action="close-account" id="id_CloseAccount">
{% csrf_token %}
<legend style="font-size:16px; color:#FF6600">Account Termination Request </legend>
<table width="600" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="62%"> Please give us the feed back or reason for closing. </td>
  </tr>
  <tr>
  <td width="38%"> <textarea name="feedback" class="form-control" id="inputFeedback"> </textarea> </td>
  </tr>
  <tr>
    <td> <button type="submit" class="btn btn-default" onclick="return confirm('Are you sure you want to close your subscription ?')"> Confirm </button> </td>
  </tr>
</table>
<div align="center" class="style1"></div>
</form>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
</script>
<script>
function confirm()
{
	if( option == true)
	{
	 	
		return true;
	}
	else
	{
	return false;
	}
}
</script>
</div>
</div>
{% endblock content %}

IndiaDens/templates/customers/CustomerConfirmed.html
{% extends 'base-home.html' %}
{% block content %}
<div style="margin-left:20%; margin-right:25%; margin-top:10%">
<div class="round-rect" style="width:400px">
<form class="form-horizontal" method="post" action="login">
{% csrf_token %}
<legend style="font-size:16px; color:#FF6600">Your account is verified.</legend>
<table width="100%" border="0" cellspacing="1" cellpadding="3">
  <tr>
    <td width="100%">Thanks for the verfication. Your account is activated. Your login credentials are already sent to the registered email. Please click <a href="/Customer/login">here</a> to login into our portal and add/modify more listings.</td>
    </tr>
</table>
<div align="center" class="style1"></div>
</form>
</div>
</div>
{% endblock content %}

IndiaDens/templates/customers/CustomerListingsPage.html
{% extends 'base.html' %}
{% block content %}

{% endblock content %}

IndiaDens/templates/customers/CustomerRegistration.html
{% extends 'base.html' %}
{% block content %}
<div style="margin-left:20%; margin-right:25%; margin-top:10%">
  <div class="round-rect" style="width:400px">
    <form class="form-horizontal" enctype="multipart/form-data" action="/Customer/customer-form" method="post">
	<input type="hidden" name="cid" value="{{cid}}" />
      {% csrf_token %}
      <p align="center" id="error">{{errmsg}}</p>
	  <p align="center">{{successmsg}}</p>
      <legend style="font-size:16px; color:#FF6600">CustomerForm </legend>
      <table width="100%" border="0" cellspacing="1" cellpadding="3">
	  <tr>
          <td>Customer Type</td>
          <td>{{form.customertype}}
            <p id="Err0"></p></td>
        </tr>
		{%if form.customertype != 1%}
	  <tr id="companyname">
          <td>Company Name </td>
          <td>{{form.title}}</td>
		  </tr>
	<tr id="subtitle">
	<td>Subtitle </td>
	<td>{{form.subtitle}}</td>
    </tr>
	{%endif%}
        <tr>
          <td>First Name </td>
          <td>{{form.firstname}}
            <p id="Err1"></p></td>
        </tr>
        <tr>
          <td >Last Name </td>
          <td>{{form.lastname}}
            <p id="Err2"></p></td>
        </tr>
		{%if not request.session.Customer%}
        <tr>
          <td>Emailid </td>
          <td>{{form.email}}
           <p>{{notification}}</p><p id="Err3"></p></td>
        </tr>
		{%endif%}
        <tr>
          <td>Contact Number </td>
          <td>{{form.phone}}
            <p id="Err5"></p></td>
        </tr>
        <tr>
          <td>Address</td>
          <td>{{form.address}}
            <p id="Err7"></p></td>
        </tr>
        <tr>
          <td>City </td>
          <td> {{form.City}}<p id="Err6">
               <input type="hidden" name="city" id="id_City-x" style="color: #CCC; position: absolute; background: transparent; z-index: 1;"/>
		 {{form.CityID.as_hidden}} </p></td>
        </tr>
        <tr>
          <td>State</td>
          <td>{{form.state}}
            <p id="Err9"></p></td>
        </tr>
		<tr>
          <td>Country</td>
          <td>{{form.country}}</td>
        </tr>
		<tr>
          <td>Fax </td>
          <td>{{form.fax}}</td>
        </tr>
		<tr>
          <td>Website </td>
          <td>{{form.website}}</td>
        </tr>
        <tr>
          <td>Logo</td>
          <td><input type="file" name="Imagefile" /></td>
        </tr>
		<tr>
          <td>Profile </td>
          <td>{{form.profile}}</td>
        </tr>
		<tr>
          <td>Deals </td>
          <td>{{form.deals}}</td>
        </tr>
		<tr>
          <td>Dealing Location </td>
          <td>{{form.dealinglocation}}</td>
        </tr>
		<tr>
          <td>Description </td>
          <td>{{form.description}}</td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td><input name="Submit" type="submit" value="submit" onclick="return customerValidate()"/></td>
        </tr>
      </table>
    </form>
  </div>
</div>
 <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
 </script>
 <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
 <script type="text/javascript" src="/static/js/jquery.mockjax.js"></script>
<script type="text/javascript" src="/static/js/jquery.autocomplete.js"></script>
<script src="/static/js/cities.js"></script>
<script>
$("#id_customertype").change(function()
{ 
	var category = $("#id_customertype").val();
	if(category == 2 || category == 3)
	{
		$("#companyname").show();
		$("#subtitle").show();
	}
	if(category == 1)
	{
	    $("#companyname").hide();
		$("#subtitle").hide();
	}
});
</script>
<script>
function customerValidate()
{
 var a = $("#id_firstname").val();
 var b = $("#id_lastname").val();
 var c = $("#id_email").val();
 var e = $("#id_phone").val();
 var g = $("#id_address").val();
 var h = $("#id_cityname").val();
 var i = $("#id_state").val();
 var j = $("#customertype").val();
 is_error=false; 
   if(a == "")
	 {
       errmsg = "Please Enter Firstname";
	   is_error = true;  
	   document.getElementById("Err1").style.color="red";
	   $("#Err1").html(errmsg);
	   $("#id_firstname").focus();
	 }
	if(b == "")
	 {
	   errmsg = "Please Enter Lastname";
	   is_error = true; 
	   document.getElementById("Err2").style.color="red";
	   $("#Err2").html(errmsg);
	   $("#id_lastname").focus();
	  }
	

	if(c == "")
	 {
	   errmsg = "Please Enter Emailid";
	   is_error = true; 
	   document.getElementById("Err3").style.color="red";
	   $("#Err3").html(errmsg);
	   $("#id_email").focus();
	  }
	if (e == "")
	   {
	     errmsg = "Please Enter Contact Number";
	   	 is_error = true;
		 document.getElementById("Err5").style.color="red";
	     $("#Err5").html(errmsg);
		 $("#id_phone").focus();		 
	   }

	if(g == "")
	{
		errmsg = "Please Enter Address";
	    is_error = true;
		document.getElementById("Err7").style.color="red";
		$("#Err7").html(errmsg);
		$("#id_address").focus();
	}



	if(h == "")
	{
		errmsg = "Please Enter City";
	    is_error = true;
		document.getElementById("Err8").style.color="red";
		$("#Err8").html(errmsg);
		$("#id_cityname").focus();
	}
    
	if(i == 0)
	{
		errmsg = "Please Select State";
	    is_error = true;
		document.getElementById("Err9").style.color="red";
		$("#Err9").html(errmsg);
		$("#id_state").focus();
	}
	if(j == 0)
	{
		errmsg = "Please Select CustomerType";
	    is_error = true;
		document.getElementById("Err0").style.color="red";
		$("#Err0").html(errmsg);
		$("#id_customertype").focus();
	}

	if(is_error)
	{
	  return false;
	}
	else
	{
	 return true;
	}
}
</script>
{% endblock content %}

IndiaDens/templates/customers/testphp.html
<html>
<head>
<title>This is my 1st php program</title>
</head>
<body>
	<?php echo "hello , world";?>
</body>
</html>