IndiaDens/Admin/urls.py
from django.conf.urls  import *
from AdminHome import *

admin_urls = patterns('Admin.views',
    url(r'^$', HomePage.as_view()),
)

IndiaDens/Customers/urls.py
from django.conf.urls  import *
from views import *
from AravindViews import *

customer_urls = patterns('Customer.views',
    url(r'^$', HomePage.as_view()),
    url(r'^login', Login.as_view()),
    url(r'^listing-form', ListingForm.as_view()),
    url(r'^customer-menu', CustomerListPage.as_view()),
    url(r'^customer-listings', CustomerListings.as_view()),
    url(r'^confirm/([A-Za-z0-9]+)$', Confirm.as_view()),
    url(r'^mobile-confirm', MobileConfirm.as_view()),
    url(r'^reset-password', ResetPassword.as_view()),
    url(r'^close-account', CloseAccount.as_view()),
    url(r'^ListDelele', CustomerListDelete.as_view()),
    url(r'^callback-requests', CustomerCallBackRequests.as_view()),
    url(r'^ajaxcallback-request', AjaxCallBackRequest.as_view()),
    url(r'^visitor-reviews', VisitorReviewList.as_view()),
    url(r'^list-delete', ListingDelete.as_view()),
    url(r'^change-password', ChangePassword.as_view()),
    url(r'^customer-form', CustomerRegistration.as_view()),
)

IndiaDens/Staff/urls.py
from django.conf.urls  import *
from views import *

staff_urls = patterns('Staff.views',
    url(r'^$', HomePage.as_view()),
    url(r'^login', Login.as_view()),
    url(r'^logout', Logout.as_view()),
    url(r'^new-listings', NewListings.as_view()),
    url(r'^change-password', ChangePassword.as_view()),
    url(r'^executive-registration', ExecutiveRegistration.as_view()),
    url(r'^employee-form', Employee.as_view()),
    url(r'^listings', Listings.as_view()),
    url(r'^listingimages', ListingImages.as_view()),
    url(r'^listing-attributes', ListingAttributes.as_view()),
    url(r'^customer-list', CustomerList.as_view()),
    url(r'^customer-delete', CustomerDelete.as_view()),
    url(r'^customer-sale-listings', CustomerSaleListings.as_view()),
    url(r'^customer-rental-listings', CustomerRentalListings.as_view()),
    url(r'^cities', Location.as_view()),
    url(r'^mobilemessages', ListMessages.as_view()),
    url(r'^delete-messages', DeleteMessages.as_view()),
    url(r'^employee-list', ExecutivesList.as_view()),
    url(r'^zap-db', ZapDb.as_view()),
    
)

IndiaDens/urls.py
from django.conf.urls import *
from Admin.urls import admin_urls
from Staff.urls import staff_urls
from Customers.urls import customer_urls
from views import *
from searchviews import *

handler500 = 'djangotoolbox.errorviews.server_error'

urlpatterns = patterns('',
    ('^_ah/warmup$', 'djangoappengine.views.warmup'),
    ('^$', HomePage.as_view()),
    ('^Admin/', include(admin_urls)),
    ('^Staff/', include(staff_urls)),
    ('^[Cc]ustomer/', include(customer_urls)),
    ('^new-listing', NewListing.as_view()),
    ('^reg-confirmation', RegConfirmation.as_view()),
    ('^logout', Logout.as_view()), 
    ('^getcities', GetCityName.as_view()),
    ('^listing-info', ListingInfo.as_view()),
    ('^mobile-message', SaveMessage.as_view()),
    ('^testmail', TestMail.as_view()),
    ('^visitor-reviewsform', VisitorReviews.as_view()),
    ('^callback-requestform', CallBackRequest.as_view()),
    ('^testajax', TestAjax.as_view()),
    ('^get-listings', SearchResults.as_view()),
    ('^visitor-login', VisitorLogin.as_view()),
    ('^confirm-code', ConfirmVisitors.as_view()),
    ('^test-slide', TestSlide.as_view()),
    ('^ajax-customerlogin', AjaxCustomerLogin.as_view()),
    ('^ajax-confirmmobile', AjaxConfirmMobile.as_view()),
    ('^whatismyip', MyIP.as_view()),
    #('^display-cities', AutoDispalyCities.as_view()),
    url(r'^testmodel', TestModel.as_view()),
)

IndiaDens/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from __future__ import unicode_literals

from django.db import models

PROPERTY_TYPES = {10:'Apartments', 20:'Independent House', 25:' Villas', 30:'Pent House', 40: 'Farm House', 50:'Office Space', 100:'Residential Lands', 110:'Commercial Lands'}
PLANS = {0: 'Free', 1:'Silver', 2:'Gold', 3:'Platinum'}

class AuthGroup(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=80L, unique=True)
    class Meta:
        db_table = 'auth_group'

class AuthGroupPermissions(models.Model):
    id = models.IntegerField(primary_key=True)
    group = models.ForeignKey(AuthGroup)
    permission = models.ForeignKey('AuthPermission')
    class Meta:
        db_table = 'auth_group_permissions'

class AuthPermission(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50L)
    content_type = models.ForeignKey('DjangoContentType')
    codename = models.CharField(max_length=100L)
    class Meta:
        db_table = 'auth_permission'

class AuthUser(models.Model):
    id = models.IntegerField(primary_key=True)
    password = models.CharField(max_length=128L)
    last_login = models.DateTimeField()
    is_superuser = models.IntegerField()
    username = models.CharField(max_length=30L, unique=True)
    first_name = models.CharField(max_length=30L)
    last_name = models.CharField(max_length=30L)
    email = models.CharField(max_length=75L)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()
    class Meta:
        db_table = 'auth_user'

class AuthUserGroups(models.Model):
    id = models.IntegerField(primary_key=True)
    user = models.ForeignKey(AuthUser)
    group = models.ForeignKey(AuthGroup)
    class Meta:
        db_table = 'auth_user_groups'

class AuthUserUserPermissions(models.Model):
    id = models.IntegerField(primary_key=True)
    user = models.ForeignKey(AuthUser)
    permission = models.ForeignKey(AuthPermission)
    class Meta:
        db_table = 'auth_user_user_permissions'

class Cities(models.Model):
    cityid = models.IntegerField(primary_key=True, db_column='CityID') # Field name made lowercase.
    name = models.CharField(max_length=50L, db_column='Name', blank=True) # Field name made lowercase.
    stateid = models.IntegerField(null=True, db_column='StateID', blank=True) # Field name made lowercase.
    isnew = models.IntegerField(null=True, db_column='IsNew', blank=True) # Field name made lowercase.

    @property
    def State(self):
      state = None
      states = States.objects.filter(stateid = self.stateid)
      if states:
         state = states[0]
      
      return state
      
    class Meta:
        db_table = 'cities'

class Customers(models.Model):
    customerid = models.IntegerField(primary_key=True, db_column='CustomerID') # Field name made lowercase.
    customertype = models.IntegerField(null=True, db_column='CustomerType', blank=True) # Field name made lowercase.
    parentid = models.IntegerField(null=True, db_column='ParentID', blank=True) # Field name made lowercase.
    title = models.CharField(max_length=255L, db_column='Title', blank=True) # Field name made lowercase.
    subtitle = models.CharField(max_length=100L, db_column='SubTitle', blank=True) # Field name made lowercase.
    firstname = models.CharField(max_length=100L, db_column='FirstName', blank=True) # Field name made lowercase.
    lastname = models.CharField(max_length=100L, db_column='LastName', blank=True) # Field name made lowercase.
    address = models.CharField(max_length=255L, db_column='Address', blank=True) # Field name made lowercase.
    cityid = models.IntegerField(null=True, db_column='CityID', blank=True) # Field name made lowercase.
    stateid = models.IntegerField(null=True, db_column='StateID', blank=True) # Field name made lowercase.
    countryid = models.IntegerField(null=True, db_column='CountryID', blank=True) # Field name made lowercase.
    phone = models.CharField(max_length=100L, db_column='Phone', blank=True) # Field name made lowercase.
    fax = models.CharField(max_length=100L, db_column='Fax', blank=True) # Field name made lowercase.
    email = models.CharField(max_length=100L, db_column='EMail', blank=True) # Field name made lowercase.
    loginpwd = models.CharField(max_length=25L, db_column='LoginPwd', blank=True) # Field name made lowercase.
    locationmap = models.CharField(max_length=255L, db_column='LocationMap', blank=True) # Field name made lowercase.
    website = models.CharField(max_length=255L, db_column='WebSite', blank=True) # Field name made lowercase.
    logo = models.CharField(max_length=255L, db_column='Logo', blank=True) # Field name made lowercase.
    profile = models.CharField(max_length=255L, db_column='Profile', blank=True) # Field name made lowercase.
    deals = models.CharField(max_length=255L, db_column='Deals', blank=True) # Field name made lowercase.
    dealinglocations = models.CharField(max_length=255L, db_column='DealingLocations', blank=True) # Field name made lowercase.
    description = models.CharField(max_length=255L, db_column='Description', blank=True) # Field name made lowercase.
    keywords = models.CharField(max_length=255L, db_column='KeyWords', blank=True) # Field name made lowercase.
    confirmcode = models.CharField(max_length=25L, db_column='ConfirmCode', blank=True) # Field name made lowercase.
    updatedby = models.IntegerField(null=True, db_column='UpdatedBy', blank=True) # Field name made lowercase.
    isconfirmed = models.IntegerField(null=True, db_column='IsConfirmed', blank=True) # Field name made lowercase.
    emailcode = models.CharField(max_length=50L, db_column='EMailCode', blank=True) # Field name made lowercase.
    isemailverified = models.IntegerField(null=True, db_column='IsEMailVerified', blank=True) # Field name made lowercase.
    ismobileverified = models.IntegerField(null=True, db_column='IsMobileVerified', blank=True) # Field name made lowercase.
    mobilecode = models.CharField(max_length=50L, db_column='MobileCode', blank=True) # Field name made lowercase.
    isdeleted = models.IntegerField(null=True, db_column='IsDeleted', blank=True) # Field name made lowercase.
    class Meta:
        db_table = 'customers'

    @property
    def State(self):
      state = States.objects.get(stateid = self.stateid)
      return state

    @property
    def City(self):
      city = Cities.objects.get(cityid = self.cityid)
      return city
    
    @property
    def Rentalcounter(self):
      counter = 0
      listing_count = Rentals.objects.filter(customerid = self.customerid)
      for i in listing_count:
        counter = counter+1
      return counter
    @property
    def Salecounter(self):
      counter = 0
      listing_count = Sales.objects.filter(customerid = self.customerid)
      for i in listing_count:
        counter = counter+1
      return counter


class DjangoContentType(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100L)
    app_label = models.CharField(max_length=100L)
    model = models.CharField(max_length=100L)
    class Meta:
        db_table = 'django_content_type'

class DjangoSession(models.Model):
    session_key = models.CharField(max_length=40L, primary_key=True)
    session_data = models.TextField()
    expire_date = models.DateTimeField()
    class Meta:
        db_table = 'django_session'

class DjangoSite(models.Model):
    id = models.IntegerField(primary_key=True)
    domain = models.CharField(max_length=100L)
    name = models.CharField(max_length=50L)
    class Meta:
        db_table = 'django_site'

class Employees(models.Model):
    employeeid = models.IntegerField(primary_key=True, db_column='EmployeeID') # Field name made lowercase.
    firstname = models.CharField(max_length=50L, db_column='FirstName', blank=True) # Field name made lowercase.
    lastname = models.CharField(max_length=50L, db_column='LastName', blank=True) # Field name made lowercase.
    title = models.CharField(max_length=100L, db_column='Title', blank=True) # Field name made lowercase.
    branchid = models.IntegerField(null=True, db_column='BranchID', blank=True) # Field name made lowercase.
    designation = models.CharField(max_length=100L, db_column='Designation', blank=True) # Field name made lowercase.
    emailid = models.CharField(max_length=100L, db_column='EMailID', blank=True) # Field name made lowercase.
    loginpwd = models.CharField(max_length=25L, db_column='LoginPwd', blank=True) # Field name made lowercase.
    contactno = models.CharField(max_length=25L, db_column='ContactNo', blank=True) # Field name made lowercase.
    role = models.CharField(max_length=1L, db_column='Role', blank=True) # Field name made lowercase.
    businesscategory = models.IntegerField(null=True, db_column='BusinessCategory', blank=True) # Field name made lowercase.
    businessinfo = models.CharField(max_length=255L, db_column='BusinessInfo', blank=True) # Field name made lowercase.
    address = models.CharField(max_length=255L, db_column='Address', blank=True) # Field name made lowercase.
    city = models.CharField(max_length=100L, db_column='City', blank=True) # Field name made lowercase.
    stateid = models.IntegerField(null=True, db_column='StateID', blank=True) # Field name made lowercase.

IndiaDens/Staff/forms.py
from django import forms

class SaleListingImages(forms.Form):
    largeimage = forms.CharField(forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:40px'}),  required=True)
    description = forms.CharField(required=True, widget=forms.Textarea)

class ExecutiveRegForm(forms.Form):
    BUSINESS_CATEGORY = [
                   ('0', "Individual"),
                   ('1', "NetCafe"),
                   ('2', "E-seva"),
                   ]
    
    firstname = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON',  'style':'width:80px'}),  required=True)
    lastname = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:80px'}),  required=True)
    title = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:80px'}),  required=False)
    emailid = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:80px'}),  required=True)
    loginpwd = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'class' : 'txt-box1', 'autocomplete':'ON',}))
    contactno=forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':10, 'style':'width:80px'}),  required=True)
    business_category=forms.ChoiceField(choices = BUSINESS_CATEGORY, widget = forms.Select(attrs={'style':'width:100px'}), required=True)
    business_info = forms.CharField(widget = forms.Textarea(attrs={'autocomplete':'ON', 'size':30, 'rows' :3, 'style':'width:200px'}),  required=False)
    address = forms.CharField(required=True, widget=forms.Textarea(attrs={'rows':4, 'style':'width:200px'}))
    City = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:80px'}),  required=True)
    CityID = forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'ON', 'style':'width:40px'}), required=False)
    state = forms.ChoiceField(choices = [], widget = forms.Select(attrs={'style':'width:100px'}), required=True) 
    
    def __init__(self, *args, **kwargs):
      states = []
      if 'states' in kwargs:
        states = kwargs.pop('states')
      super(ExecutiveRegForm, self).__init__(*args,**kwargs)
      self.fields['state'].choices = states 
    
class EmployeeRegForm(forms.Form):
    
    firstname = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON',  'style':'width:90px',}),  required=True)
    lastname = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:90px'}),  required=True)
    emailid = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:100px'}),  required=True)
    loginpwd = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'class' : 'txt-box1', 'autocomplete':'ON',}))
    contactno=forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:100px'}),  required=True)
    address = forms.CharField(required=True, widget=forms.Textarea(attrs={'rows':4, 'style':'width:200px'}))
    City = forms.CharField(widget = forms.TextInput(attrs={'autocomplete':'ON', 'size':30, 'style':'width:80px'}),  required=True)
    CityID = forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'ON', 'style':'width:80px'}), required=False)
    state = forms.ChoiceField(choices = [], widget = forms.Select(attrs={'style':'width:100px'}), required=True)
    
    def __init__(self, *args, **kwargs):
      states = []
      if 'states' in kwargs:
        states = kwargs.pop('states')
      super(EmployeeRegForm, self).__init__(*args,**kwargs)
      self.fields['state'].choices = states  
            
  
  
  
  

IndiaDens/Admin/views.py
from IndiaDens.Admin import *


class HomePage(TemplateView):

  def get(self, request, *args, **kwargs):  
    content = {}
    return render_to_response("Admin/Index.html")


IndiaDens/templates/CallbackRequestForm.html
{% extends 'base.html' %}
{% block content %}
<div style="margin-left:20%; margin-right:25%; margin-top:10%">
  <div class="round-rect" style="width:400px">
    <form class="form-horizontal" action="callback-requestform" method="post">
      {% csrf_token %}
      <legend style="font-size:16px; color:#FF6600">Callback Request Form</legend>
      <table width="100%" border="0" cellspacing="1" cellpadding="3">
        <tr>
          <td> Name </td>
          <td>{{form.name}}
            <p id="Err1"></p></td>
        </tr>
        <tr>
          <td>Emailid </td>
          <td>{{form.email}}
            <p id="Err3"></p></td>
        </tr>
        <tr>
          <td>Contact Number </td>
          <td>{{form.phone}}
            <p id="Err5"></p></td>
			<td>{{form.CustomerId}}</td>
			<td>{{form.ListingId}}</td>
			<td>{{form.ListingType}}</td>
        </tr>
        <tr>
          <td>Preferable Time1</td>
          <td>{{form.pftime1}}
            <p id="Err7"></p></td>
        </tr>
		<tr>
          <td>Preferable Time2</td>
          <td>{{form.pftime2}}
            <p id="Err7"></p></td>
        </tr>
		<tr>
          <td>Preferable Time3</td>
          <td>{{form.pftime3}}
            <p id="Err7"></p></td>
        </tr>
        <tr>
          <td>Message</td>
          <td>{{form.message}}
            <p id="Err9"></p></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td><input name="Submit" type="submit" value="submit" /></td>
        </tr>
      </table>
    </form>
  </div>
</div>
{% endblock content %}

IndiaDens/templates/EMail-ExistingCustomer.html
<style type="text/css">
<!--
.style4 {
	font-size: large;
	color: #990000;
}
.style5 {
	font-size: large;
	font-weight: bold;
	color: #663399;
}
-->
</style>
<div class="round-rect" style="width:800px">
<legend style="font-size:16px; color:#FF6600">Dear {{first_name}} {{last_name}} </legend>
<p>Thank you for choosing <a href="http://www.indiadens.com" target="_blank">IndiaDens.com</a> as your favorite property ads media. </p>
<P>You are trying to add new listings without login.</P>
<p>You are have listings we need your approval please login to our site with your login credentials</P>
<P> Here is your listings</P>
<table width="600" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td>Title</td>
  </tr>
  {% for slist in salelistings %}
  <tr>
  <td>{{slist.title}}</td>
  </tr>
 {% endfor %}
</table>
<table width="600" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td>Title</td>
  </tr>
  {% for rlist in rentallistings %}
  <tr>
    <td>{{rlist.title}}</td>
  </tr>
  {% endfor %}
</table>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p> Please <a href="{{login_link}}"> click here</a> to login into our site and approve your listings</p>
</div>

IndiaDens/templates/Index.html
{% extends 'base-home.html' %}
{% block content %}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.mockjax.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.autocomplete.js"></script>

<table width="100%" border="0" cellspacing="0" cellpadding="3">
  <tr><td><span style="color:#FF6633; font-style:normal"><u>WHEREVER YOU GO. YOU CAN FIND HOME</u></span></td><td align="right">Advertise your Property <a href="/new-listing?type=2">For Rent</a> or <a href="/new-listing?type=1">For Sale</a> </td></tr>
  <tr>
    <td width="300" valign="top"><img src="{{ STATIC_URL }}images/home.jpg" /></td>
    <td><div id="content">
        <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
          <li class="active"><a href="#red" data-toggle="tab" style="width:100px">For Rent</a></li>
          <li><a href="#orange" data-toggle="tab" style="width:100px">For Sale</a></li>
        </ul>
        <form action="/get-listings" method="post">
          {% csrf_token %}
		  <div class="form-horizontal" style="min-height:150px;">
            <div style="height:50px"> Property Type
              <select name="PropertyType" style="width:200px">
                <option value="10">Residential Apartments</option>
                <option value="20">Independent Homes/Villas</option>
                <option value="30">Pent House</option>
                <option value="40">Farm House</option>
                <option value="50">Office Space</option>
                <option value="100">Residential Lands</option>
                <option value="110">Commercial Lands</option>
              </select>
              City&nbsp;
              <input type="text" name="city" id="id_City"  value="{{City}}" style="width:150px"/>
              <input type="hidden" name="city" id="id_City-x" disabled="disabled" style="color: #CCC; position: absolute; background: transparent; z-index: 1;"/>
              <input type="hidden" name="cityid" id="id_CityID" style="position: absolute; z-index: 2; background: transparent;"/>
              <input type="hidden" name="type" id="id_type" value="1" style="position: absolute; z-index: 2; background: transparent;"/>
            </div>
            <div style="height:50px">
             Bedrooms <select name="Bedrooms" style="width:150px">
               <option value="0">Any</option>
               <option value="1">Single Bedroom</option>
               <option value="2">Double Bedroom</option>
               <option value="3">Triple Bedroom</option>
               <option value="4">Four Bedroom</option>
               <option value="5">Five or More</option>
             </select> Preferred Location <input name="location" type="text" maxlength="80"  size="80" />
            </div>
            <div style="height:50px"> Budget
              <input type="text" name="minprice" value="0" placeholder='Min' style="width:60px">
              &nbsp;
              <input type="text" name="maxprice" value="0" placeholder='Max' style="width:60px">
              Area
              <input type="text" name="minarea" value="900" placeholder='Min' style="width:50px">
              &nbsp;
              <input type="text" name="maxarea" value="0" placeholder="Max" style="width:50px">
              &nbsp;
              <select name="AreaUnit" style="width:80px">
                <option value="1">Sq.Ft.</option>
                <option value="2">Sq. Mt.</option>
                <option value="3">Sq. Yd.</option>
                <option value="4">Acres</option>
              </select>
            </div>
          </div>
		  
          <div id="my-tab-content" class="tab-content">
            <div class="tab-pane active form-horizontal" id="red" style="height:50px">
              <span style="color:blue; cursor:pointer" id="Tab">Click here to refine more</span> (You can refine the search by selecting morefacilities and restructions)
              <div id="AdvancedSearch" style="display:none">
                <div style="height:50px">
                  <p>Rent Advance
                    <input type="text" name="advance_minprice" value="0" placeholder='Min' style="width:80px">
                    &nbsp;
                    <input type="text" name="advance_maxprice" value="0" placeholder='Max' style="width:80px">
                    Bachelors Allowed&nbsp;
                    <input name="bachelors_allowed" type="checkbox" value="checkbox" checked="checked" />
                    Families Allowed
                    <input name="families_allowed" type="checkbox" value="checkbox" checked="checked" />
                  </p>
                  <p>Other Facilities: Lift
                    <input name="lift" type="checkbox" value="checkbox" />
                    Swimming Pool
                    <input name="swimmingpool" type="checkbox" value="checkbox" />
                    Gated Community
                    <input name="gated_community" type="checkbox" value="checkbox" />
                    Power Backup
                    <input name="power_backup" type="checkbox" value="checkbox" />
                    Furnished
                    <input name="furnished" type="checkbox" value="checkbox" />
                    Facing
                    <select name="facing" style="width:80px">
                      <option value="0">Any</option>
                      <option value="1">East</option>
                      <option value="2">West</option>
                      <option value="3">South</option>
                      <option value="4"></option>
                    </select>
                  </p>
                </div>
              </div>
            </div>
            <div class="tab-pane" id="orange">&nbsp;</div>
			<br />			<br />
            <div align="center">
              <input name="cmdSearch" type="submit" value="Get Listings" class='btn'/>
            </div>
          </div>
        </form>
        </div></td>
  </tr>
  <tr>
    <td colspan="2" valign="top" class="fotercenter" height="300px">&nbsp;</td>
  </tr>
</table>
 <script>   
       $("#Tab").click(function(){
       $("#AdvancedSearch").slideToggle(300);
	   });
</script>
<script src="{{ STATIC_URL }}js/cities.js"></script>
{% endblock content %}

IndiaDens/templates/TestAjax.html
{% extends 'base.html' %}
{% block content %}
<div id="divBody"  style="min-height:600px">
<p>Type city name in english:</p>
<div style="position: relative; height: 80px;">
  <input type="text" name="city" id="id_City" style="position: absolute; z-index: 2; background: transparent;"/>
  <input type="text" name="city" id="id_City-x" disabled="disabled" style="color: #CCC; position: absolute; background: transparent; z-index: 1;"/>
</div>
<input type="text" name="city" id="id_CityID" style="position: absolute; z-index: 2; background: transparent;"/>
</div>

<div id="selction-ajax"></div>
{% endblock content %}